
import React, { Component } from 'react'
import GoogleLogin from 'react-google-login'

import Head from 'next/head'
import styles from '../styles/Home.module.css'

export class App extends Component {

  responseGoogle = (response) => {
    console.log(response);
    console.log(response.profileObj);
  }

  render() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <GoogleLogin
            clientId="585461355287-25mcae0i1ur704kaek9ukuohkm7na77m.apps.googleusercontent.com"
            buttonText="Login"
            onSuccess={this.responseGoogle}
            onFailure={this.responseGoogle}
            cookiePolicy={'single_host_origin'}
          >

          </GoogleLogin>
        </main>
      </div>
    )
  }
}

export default App
